### ISSUE TITLE
对于维基百科是诈骗网站的怀疑以及对其他境外网站的蔑视而感到不满

### ISSUE THREAD

**Issue by ghost** [welovexjp/welovexjp.github.io#1]
在[辟谣系列（一）：还原所谓“六四事件”的真相](https://welovexjp.github.io/post/pi-yao-xi-lie-yi-huan-yuan-suo-wei-liu-si-shi-jian-de-zhen-xiang/)中，你认为维基百科是诈骗网站，认为“维基百科本身就是一个不真实存在的对虚假网站”，在其他地方不能访问。然而，这不过是因为中国政府把它给墙了，根本不可能出现赌博网站。而所述“打着网络百科全书之旗，却行网络诱骗之实，堂而皇之的将收款信息顶置在网页最显眼的地方，企图以“捐款”的名义骗取网民财产。“。 呵呵，就一个不起眼的donate叫最显眼的地方？而且都是自愿捐款，也完全没有误导信息。相反，百度上放置各种广告才是逼迫付款，像这种无广告自由的百科哪里找？此外，关于“于忧徒步（Youtube）、颓特（Twitter）、非死不可（Facebook）等境外非法网站”上，其他外国人都上的东西怎能叫非法？而且国内的微博是抄twitter的,youku看名字就知道抄了谁，包括你现在发表文章的平台也是国外的网站。所以微博就是比颓特更垃圾的垃圾中的战斗机。不是老说老外歧视中国人吗，那子所不欲勿施于人，不要也歧视外国人。你们这种严重的扭曲事实比你们所批评老外的还严重。至此对此文章表示强烈不满！

**Comment by lonelyjunkman** [comment]
> 

我感觉如果六四如外国媒体报道的一般，那么中共的沉默和封锁就是最好的回答。网页内容发布的时间显示是2019.6.1，正好是六四30周年的前几天，究竟是高级黑还是低级红，答案如何不言自明

**Comment by Fightxing** [comment]
我觉得吧，这篇文章完全是在讽刺；这篇文章非常好的诠释了高级黑🤣

**Comment by Fightxing** [comment]
> 在[辟谣系列（一）：还原所谓“六四事件”的真相](https://welovexjp.github.io/post/pi-yao-xi-lie-yi-huan-yuan-suo-wei-liu-si-shi-jian-de-zhen-xiang/)中，你认为维基百科是诈骗网站，认为“维基百科本身就是一个不真实存在的对虚假网站”，在其他地方不能访问。然而，这不过是因为中国政府把它给墙了，根本不可能出现赌博网站。而所述“打着网络百科全书之旗，却行网络诱骗之实，堂而皇之的将收款信息顶置在网页最显眼的地方，企图以“捐款”的名义骗取网民财产。“。 呵呵，就一个不起眼的donate叫最显眼的地方？而且都是自愿捐款，也完全没有误导信息。相反，百度上放置各种广告才是逼迫付款，像这种无广告自由的百科哪里找？此外，关于“于忧徒步（Youtube）、颓特（Twitter）、非死不可（Facebook）等境外非法网站”上，其他外国人都上的东西怎能叫非法？而且国内的微博是抄twitter的,youku看名字就知道抄了谁，包括你现在发表文章的平台也是国外的网站。所以微博就是比颓特更垃圾的垃圾中的战斗机。不是老说老外歧视中国人吗，那子所不欲勿施于人，不要也歧视外国人。你们这种严重的扭曲事实比你们所批评老外的还严重。至此对此文章表示强烈不满！

看，一个老实人
